### ISSUE TITLE
Ambiguous and missing nodes

### ISSUE THREAD

**Issue by sebescudie** [vvvv/VL.IO.WebSocket#3]
Hey there,

Just installed the latest preview version `0.6.0-alpha` on vvvv gamma `5.0-preview20`. When running the help patch "Send and receive data", the `Split (WSMessage)` node throws an "Object not set [..]" exception when banging "Send Data" :

<img src="https://github.com/vvvv/VL.IO.WebSocket/assets/8690430/94fd20d3-6e7c-45b5-b556-ef614743932f" width="500">

After looking inside the lib, it looks like there are missing nodes/ambiguities here and there. For instance, this is the aforementioned `Split` node :

<img src="https://github.com/vvvv/VL.IO.WebSocket/assets/8690430/76a6d879-a2a1-4c30-abb7-ba2d3bbf8526" width="300">

The `WebSocketServer` also has a bunch of missing nodes.

**Comment by joreg** [comment]
grr. thanks for pointing this out. forgot to commit the nuspec with the correct required dependency. please check build 0.7.0-alpha
